# Generated by Django 3.0.8 on 2020-08-02 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorldSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.TextField()),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('who', models.ManyToManyField(blank=True, to='herolog.Person')),
            ],
        ),
    ]
